export const SystemParams = {
    PAGINATION_SIZE: 'PAGINATION_SIZE',
    THEME_DEFAULT: 'THEME_DEFAULT',
    VIP_MIN_SCORE: 'VIP_MIN_SCORE',
    RISK_DAYS_THRESHOLD: 'RISK_DAYS_THRESHOLD',
    SCORE_WEIGHT_VISIT: 'SCORE_WEIGHT_VISIT',
    SCORE_DIVISOR_SPEND: 'SCORE_DIVISOR_SPEND',
    NEW_CLIENT_LIMIT_DAYS: 'NEW_CLIENT_LIMIT_DAYS'
};
